USE [master]
GO

/****** Object:  Database [Kalorienbilanz]    Script Date: 10.07.2023 15:28:28 ******/
CREATE DATABASE [Kalorienbilanz]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Kalorienbilanz', FILENAME = N'C:\SQL-Kurs\DB\Kalorienbilanz\Kalorienbilanz.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Kalorienbilanz_log', FILENAME = N'C:\SQL-Kurs\DB\Kalorienbilanz\Kalorienbilanz_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Kalorienbilanz].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Kalorienbilanz] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Kalorienbilanz] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Kalorienbilanz] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Kalorienbilanz] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Kalorienbilanz] SET ARITHABORT OFF 
GO

ALTER DATABASE [Kalorienbilanz] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Kalorienbilanz] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Kalorienbilanz] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Kalorienbilanz] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Kalorienbilanz] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Kalorienbilanz] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Kalorienbilanz] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Kalorienbilanz] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Kalorienbilanz] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Kalorienbilanz] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Kalorienbilanz] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Kalorienbilanz] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Kalorienbilanz] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Kalorienbilanz] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Kalorienbilanz] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Kalorienbilanz] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Kalorienbilanz] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Kalorienbilanz] SET RECOVERY FULL 
GO

ALTER DATABASE [Kalorienbilanz] SET  MULTI_USER 
GO

ALTER DATABASE [Kalorienbilanz] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Kalorienbilanz] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Kalorienbilanz] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Kalorienbilanz] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Kalorienbilanz] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Kalorienbilanz] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Kalorienbilanz] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Kalorienbilanz] SET  READ_WRITE 
GO


